# Generated by Django 4.1.2 on 2022-11-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=150)),
                ('duration_ms', models.IntegerField()),
                ('popularity', models.IntegerField()),
            ],
            options={
                'ordering': ['artist_name', 'popularity'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('number_of_tracks', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='cover')),
                ('track', models.ManyToManyField(to='playlists.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number_of_tracks'],
            },
        ),
    ]
