# Generated by Django 4.1.2 on 2022-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='number_of_tracks',
            field=models.IntegerField(null=True),
        ),
    ]
