# Generated by Django 4.1.2 on 2022-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(),
        ),
    ]
