# Generated by Django 4.1.2 on 2022-11-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_number_of_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
