# Generated by Django 4.1.2 on 2022-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.CharField(max_length=1000),
        ),
    ]
