# Generated by Django 4.1.2 on 2022-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_playlist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='url',
            field=models.BooleanField(default=True),
        ),
    ]
