# Generated by Django 4.1.2 on 2022-11-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_playlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
