# Generated by Django 4.1.2 on 2022-11-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_alter_track_duration_ms_alter_track_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
