# Generated by Django 4.1.2 on 2022-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='track',
            name='album_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
