# Generated by Django 4.1.2 on 2022-11-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_track_album_id_track_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
    ]
