# Generated by Django 4.1.2 on 2022-11-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_remove_track_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='album_name',
        ),
    ]
