# Generated by Django 4.1.2 on 2022-11-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0010_remove_track_album_id_remove_track_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='track',
        ),
    ]
