# Generated by Django 4.1.2 on 2022-11-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0012_playlistwithtrack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistwithtrack',
            options={'ordering': ['playlist']},
        ),
    ]
