# Generated by Django 4.1.2 on 2022-11-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0013_alter_playlistwithtrack_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
