# Generated by Django 4.1.2 on 2022-11-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0014_track_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
