# Generated by Django 4.1.2 on 2022-11-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0015_alter_playlist_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
