# Generated by Django 4.1.2 on 2022-11-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0016_alter_playlist_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='No description provide', max_length=100),
        ),
    ]
