# Generated by Django 4.1.2 on 2022-11-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0017_track_duration_alter_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.CharField(default='https://i0.wp.com/lesoreillescurieuses.com/wp-content/uploads/2017/07/arcade-fire-everything-now.jpg?w=640&ssl=1', max_length=1000),
        ),
    ]
