# Generated by Django 4.1.2 on 2022-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0018_alter_playlist_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.CharField(default='https://p.scdn.co/mp3-preview/135c5c2caba0db75f946dec7e93fdb752fe8d399?cid=533e61a793454e5387d1c5c2ab7208d8', max_length=1000),
        ),
    ]
