# Generated by Django 4.1.2 on 2022-11-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0019_track_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='No description provide', max_length=1000),
        ),
    ]
