version: '3.4'

networks:
  default:
    driver: bridge
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql