# Generated by Django 4.1.2 on 2022-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_username',
            field=models.CharField(default='error', max_length=50, verbose_name="spotify_username"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('ADMIN', 'Administrateur')], default='USER', max_length=30, verbose_name='Rôle'),
        ),
    ]
