# Generated by Django 4.1.2 on 2022-11-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_spotify_username_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_username',
            field=models.CharField(default='error', max_length=50),
        ),
    ]
