# Generated by Django 4.1.2 on 2022-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role_alter_user_spotify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('ADMIN', 'Administrateur')], default='USER', max_length=30, verbose_name='Rôle'),
        ),
    ]
